global:
  scrape_interval: 15s
  scrape_timeout: 4s

scrape_configs:
  - job_name: 'vortex-api'
    metrics_path: /metrics/judge-vortex
    static_configs:
      - targets: ['host.docker.internal:80']

  - job_name: 'config-control'
    metrics_path: /metrics/config-control
    static_configs:
      - targets: ['host.docker.internal:80']

  - job_name: 'distributed-rate-limiter'
    metrics_path: /metrics/distributed-rate-limiter
    static_configs:
      - targets: ['host.docker.internal:80']
