global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'vortex-executors'
    static_configs:
      - targets:
          - 'executor-core:8001'
          - 'executor-java:8002'

  - job_name: 'vortex-api'
    static_configs:
      - targets: ['host.docker.internal:53562']

  - job_name: 'config-control'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'distributed-rate-limiter'
    static_configs:
      - targets: ['host.docker.internal:8000']
