# Generated by Django 5.2.7 on 2026-03-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_remove_submission_problem_alter_submission_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
