# Generated by Django 5.2.7 on 2026-03-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
