# Generated by Django 5.2.7 on 2026-03-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_examquestion_submission_awarded_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroom',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
