# Generated by Django 5.2.12 on 2026-03-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_examroom_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('PASSED', 'Passed'), ('WRONG_ANSWER', 'Wrong Answer'), ('EXECUTED', 'Executed'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RUNTIME_ERROR', 'Runtime Error'), ('COMPILATION_ERROR', 'Compilation Error'), ('SYSTEM_ERROR', 'System Error')], default='PENDING', max_length=25),
        ),
    ]
