# Generated by Django 5.2.12 on 2026-03-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='passed_testcases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_testcases',
            field=models.IntegerField(default=0),
        ),
    ]
