# Generated by Django 5.2.12 on 2026-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_roomparticipant_access_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='visible_expected_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='visible_testcase_input',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='entry_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
